public final class io.vertx.core.impl.future.FailedFuture extends io.vertx.core.impl.future.FutureBase
{
private final java.lang.Throwable cause;
public void <init>(java.lang.Throwable)
{
java.lang.Throwable v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: java.lang.Throwable;
specialinvoke v0.<io.vertx.core.impl.future.FailedFuture: void <init>(io.vertx.core.impl.ContextInternal,java.lang.Throwable)>(null, v1);
return;
}
public void <init>(io.vertx.core.impl.ContextInternal, java.lang.Throwable)
{
java.lang.Throwable v2, v3;
io.vertx.core.impl.NoStackTraceThrowable v4;
io.vertx.core.impl.ContextInternal v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.impl.ContextInternal;
v2 := @parameter1: java.lang.Throwable;
specialinvoke v0.<io.vertx.core.impl.future.FutureBase: void <init>(io.vertx.core.impl.ContextInternal)>(v1);
if v2 == null goto label1;
v3 = v2;
goto label2;
label1:
v4 = new io.vertx.core.impl.NoStackTraceThrowable;
v3 = v4;
specialinvoke v4.<io.vertx.core.impl.NoStackTraceThrowable: void <init>(java.lang.String)>(null);
label2:
v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause> = v3;
return;
}
public void <init>(java.lang.String)
{
java.lang.String v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: java.lang.String;
specialinvoke v0.<io.vertx.core.impl.future.FailedFuture: void <init>(io.vertx.core.impl.ContextInternal,java.lang.String)>(null, v1);
return;
}
public void <init>(io.vertx.core.impl.ContextInternal, java.lang.String)
{
io.vertx.core.impl.NoStackTraceThrowable v3;
io.vertx.core.impl.ContextInternal v1;
java.lang.String v2;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.impl.ContextInternal;
v2 := @parameter1: java.lang.String;
v3 = new io.vertx.core.impl.NoStackTraceThrowable;
specialinvoke v3.<io.vertx.core.impl.NoStackTraceThrowable: void <init>(java.lang.String)>(v2);
specialinvoke v0.<io.vertx.core.impl.future.FailedFuture: void <init>(io.vertx.core.impl.ContextInternal,java.lang.Throwable)>(v1, v3);
return;
}
public boolean isComplete()
{
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
return 1;
}
public io.vertx.core.Future onComplete(io.vertx.core.Handler)
{
java.lang.Throwable v3;
io.vertx.core.impl.ContextInternal v4, v5;
io.vertx.core.Handler v1;
io.vertx.core.impl.future.FailedFuture v0;
boolean v2;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.Handler;
v2 = v1 instanceof io.vertx.core.impl.future.Listener;
if v2 == 0 goto label1;
v3 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
virtualinvoke v0.<io.vertx.core.impl.future.FailedFuture: void emitFailure(java.lang.Throwable,io.vertx.core.impl.future.Listener)>(v3, v1);
goto label3;
label1:
v4 = v0.<io.vertx.core.impl.future.FailedFuture: io.vertx.core.impl.ContextInternal context>;
if v4 == null goto label2;
v5 = v0.<io.vertx.core.impl.future.FailedFuture: io.vertx.core.impl.ContextInternal context>;
interfaceinvoke v5.<io.vertx.core.impl.ContextInternal: void emit(java.lang.Object,io.vertx.core.Handler)>(v0, v1);
goto label3;
label2:
interfaceinvoke v1.<io.vertx.core.Handler: void handle(java.lang.Object)>(v0);
label3:
return v0;
}
public io.vertx.core.Future onSuccess(io.vertx.core.Handler)
{
io.vertx.core.Handler v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.Handler;
return v0;
}
public io.vertx.core.Future onFailure(io.vertx.core.Handler)
{
java.lang.Throwable v4, v5;
io.vertx.core.impl.ContextInternal v2, v3;
io.vertx.core.Handler v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.Handler;
v2 = v0.<io.vertx.core.impl.future.FailedFuture: io.vertx.core.impl.ContextInternal context>;
if v2 == null goto label1;
v3 = v0.<io.vertx.core.impl.future.FailedFuture: io.vertx.core.impl.ContextInternal context>;
v4 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
interfaceinvoke v3.<io.vertx.core.impl.ContextInternal: void emit(java.lang.Object,io.vertx.core.Handler)>(v4, v1);
goto label2;
label1:
v5 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
interfaceinvoke v1.<io.vertx.core.Handler: void handle(java.lang.Object)>(v5);
label2:
return v0;
}
public void addListener(io.vertx.core.impl.future.Listener)
{
java.lang.Throwable v2;
io.vertx.core.impl.future.Listener v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: io.vertx.core.impl.future.Listener;
v2 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
virtualinvoke v0.<io.vertx.core.impl.future.FailedFuture: void emitFailure(java.lang.Throwable,io.vertx.core.impl.future.Listener)>(v2, v1);
return;
}
public java.lang.Object result()
{
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
return null;
}
public java.lang.Throwable cause()
{
java.lang.Throwable v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
return v1;
}
public boolean succeeded()
{
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
return 0;
}
public boolean failed()
{
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
return 1;
}
public io.vertx.core.Future map(java.util.function.Function)
{
io.vertx.core.impl.future.FailedFuture v0;
java.util.function.Function v1;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: java.util.function.Function;
return v0;
}
public io.vertx.core.Future map(java.lang.Object)
{
java.lang.Object v1;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: java.lang.Object;
return v0;
}
public io.vertx.core.Future otherwise(java.lang.Object)
{
io.vertx.core.impl.ContextInternal v3;
java.lang.Object v1;
io.vertx.core.impl.future.FailedFuture v0;
io.vertx.core.impl.future.SucceededFuture v2;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 := @parameter0: java.lang.Object;
v2 = new io.vertx.core.impl.future.SucceededFuture;
v3 = v0.<io.vertx.core.impl.future.FailedFuture: io.vertx.core.impl.ContextInternal context>;
specialinvoke v2.<io.vertx.core.impl.future.SucceededFuture: void <init>(io.vertx.core.impl.ContextInternal,java.lang.Object)>(v3, v1);
return v2;
}
public java.lang.String toString()
{
java.lang.Throwable v1;
java.lang.String v2, v3;
io.vertx.core.impl.future.FailedFuture v0;
v0 := @this: io.vertx.core.impl.future.FailedFuture;
v1 = v0.<io.vertx.core.impl.future.FailedFuture: java.lang.Throwable cause>;
v2 = virtualinvoke v1.<java.lang.Throwable: java.lang.String getMessage()>();
v3 = dynamicinvoke "makeConcatWithConstants" <java.lang.String (java.lang.String)>(v2) <java.lang.invoke.StringConcatFactory: java.lang.invoke.CallSite makeConcatWithConstants(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.String,java.lang.Object[])>("Future{cause=\u0001}");
return v3;
}
}