class io.vertx.core.impl.future.FutureImpl$3 extends java.lang.Object implements io.vertx.core.impl.future.Listener
{
final io.vertx.core.Handler val$handler;
final io.vertx.core.impl.future.FutureImpl this$0;
void <init>(io.vertx.core.impl.future.FutureImpl, io.vertx.core.Handler)
{
io.vertx.core.impl.future.FutureImpl v1;
io.vertx.core.impl.future.FutureImpl$3 v0;
io.vertx.core.Handler v2;
v0 := @this: io.vertx.core.impl.future.FutureImpl$3;
v1 := @parameter0: io.vertx.core.impl.future.FutureImpl;
v2 := @parameter1: io.vertx.core.Handler;
v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0> = v1;
v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.Handler val$handler> = v2;
specialinvoke v0.<java.lang.Object: void <init>()>();
return;
}
public void onSuccess(java.lang.Object)
{
io.vertx.core.impl.future.FutureImpl v3, v5, v7;
io.vertx.core.impl.future.FutureImpl$3 v0;
java.lang.Throwable v4;
io.vertx.core.impl.ContextInternal v6, v8;
java.lang.Object v1;
io.vertx.core.Handler v2;
v0 := @this: io.vertx.core.impl.future.FutureImpl$3;
v1 := @parameter0: java.lang.Object;
label1:
v2 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.Handler val$handler>;
v3 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
interfaceinvoke v2.<io.vertx.core.Handler: void handle(java.lang.Object)>(v3);
label2:
goto label5;
label3:
v4 := @caughtexception;
v5 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
v6 = v5.<io.vertx.core.impl.future.FutureImpl: io.vertx.core.impl.ContextInternal context>;
if v6 == null goto label4;
v7 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
v8 = v7.<io.vertx.core.impl.future.FutureImpl: io.vertx.core.impl.ContextInternal context>;
interfaceinvoke v8.<io.vertx.core.impl.ContextInternal: void reportException(java.lang.Throwable)>(v4);
goto label5;
label4:
throw v4;
label5:
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
public void onFailure(java.lang.Throwable)
{
io.vertx.core.impl.future.FutureImpl v3, v5, v7;
io.vertx.core.impl.future.FutureImpl$3 v0;
java.lang.Throwable v1, v4;
io.vertx.core.impl.ContextInternal v6, v8;
io.vertx.core.Handler v2;
v0 := @this: io.vertx.core.impl.future.FutureImpl$3;
v1 := @parameter0: java.lang.Throwable;
label1:
v2 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.Handler val$handler>;
v3 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
interfaceinvoke v2.<io.vertx.core.Handler: void handle(java.lang.Object)>(v3);
label2:
goto label5;
label3:
v4 := @caughtexception;
v5 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
v6 = v5.<io.vertx.core.impl.future.FutureImpl: io.vertx.core.impl.ContextInternal context>;
if v6 == null goto label4;
v7 = v0.<io.vertx.core.impl.future.FutureImpl$3: io.vertx.core.impl.future.FutureImpl this$0>;
v8 = v7.<io.vertx.core.impl.future.FutureImpl: io.vertx.core.impl.ContextInternal context>;
interfaceinvoke v8.<io.vertx.core.impl.ContextInternal: void reportException(java.lang.Throwable)>(v4);
goto label5;
label4:
throw v4;
label5:
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
}