class io.vertx.core.impl.future.Otherwise extends io.vertx.core.impl.future.Operation implements io.vertx.core.impl.future.Listener
{
private final java.util.function.Function mapper;
void <init>(io.vertx.core.impl.ContextInternal, java.util.function.Function)
{
io.vertx.core.impl.future.Otherwise v0;
io.vertx.core.impl.ContextInternal v1;
java.util.function.Function v2;
v0 := @this: io.vertx.core.impl.future.Otherwise;
v1 := @parameter0: io.vertx.core.impl.ContextInternal;
v2 := @parameter1: java.util.function.Function;
specialinvoke v0.<io.vertx.core.impl.future.Operation: void <init>(io.vertx.core.impl.ContextInternal)>(v1);
v0.<io.vertx.core.impl.future.Otherwise: java.util.function.Function mapper> = v2;
return;
}
public void onSuccess(java.lang.Object)
{
io.vertx.core.impl.future.Otherwise v0;
java.lang.Object v1;
v0 := @this: io.vertx.core.impl.future.Otherwise;
v1 := @parameter0: java.lang.Object;
virtualinvoke v0.<io.vertx.core.impl.future.Otherwise: boolean tryComplete(java.lang.Object)>(v1);
return;
}
public void onFailure(java.lang.Throwable)
{
io.vertx.core.impl.future.Otherwise v0;
java.lang.Throwable v1, v4;
java.lang.Object v3;
java.util.function.Function v2;
v0 := @this: io.vertx.core.impl.future.Otherwise;
v1 := @parameter0: java.lang.Throwable;
label1:
v2 = v0.<io.vertx.core.impl.future.Otherwise: java.util.function.Function mapper>;
v3 = interfaceinvoke v2.<java.util.function.Function: java.lang.Object apply(java.lang.Object)>(v1);
label2:
goto label4;
label3:
v4 := @caughtexception;
virtualinvoke v0.<io.vertx.core.impl.future.Otherwise: boolean tryFail(java.lang.Throwable)>(v4);
return;
label4:
virtualinvoke v0.<io.vertx.core.impl.future.Otherwise: boolean tryComplete(java.lang.Object)>(v3);
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
}